--
-- Kingbase database dump
--

-- Dumped from database version 12.1
-- Dumped by sys_dump version 12.1

-- Started on 2025-06-26 21:03:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'GBK';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public', false);
SET exclude_reserved_words = '';
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 589 (class 1259 OID 16400)
-- Name: user; Type: TABLE; Schema: public; Owner: system
--

CREATE TABLE public.`user` (
    id bigint NOT NULL,
    company character varying(255 char) NOT NULL,
    username character varying(255 char) NOT NULL,
    password character varying(255 char) NOT NULL,
    nickname character varying(255 char) NOT NULL,
    phone character varying(255 char),
    email character varying(255 char),
    gender smallint NOT NULL,
    status smallint NOT NULL,
    is_super smallint NOT NULL,
    create_time timestamp NOT NULL
);


ALTER TABLE public.`user` OWNER TO system;

--
-- TOC entry 588 (class 1259 OID 16398)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: system
--

ALTER TABLE public.`user` ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 9479 (class 0 OID 16400)
-- Dependencies: 589
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: system
--

COPY public.`user` (id, company, username, password, nickname, phone, email, gender, status, is_super, create_time) FROM stdin;
1	1	admin	12345678	π‹¿Ì‘±		\N	1	0	1	2025-06-21 19:56:37
2		test001	123456	test	13636366363		1	0	0	2025-06-26 17:05:53
3		user001	123456	001			1	0	0	2025-06-26 20:43:33
\.


--
-- TOC entry 9486 (class 0 OID 0)
-- Dependencies: 588
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: system
--

SELECT pg_catalog.setval('public.user_id_seq', 3, true);


--
-- TOC entry 9038 (class 2606 OID 16407)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: system
--

ALTER TABLE ONLY public.`user`
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 9036 (class 1259 OID 16408)
-- Name: company_id; Type: INDEX; Schema: public; Owner: system
--

CREATE INDEX company_id ON public."user" USING btree (company NULLS FIRST);


-- Completed on 2025-06-26 21:03:27

--
-- Kingbase database dump complete
--

